In [6]:
type(df)

pandas.DataFrame

In [9]:
import pandas as pd
df=pd.read_csv('emp.csv')
df

    eno    ename  salary  deptno         doj
0    10    Amber    1000      10  2018-05-14
1     2     Amar    1000      10  2017-03-22
2     8    Sagar    1000      20  2020-11-30
3     4   Thomas    1000      10  2019-08-18
4     5     Jade    2000      10  2021-02-10
5     6    Smith    1000      10  2016-12-01
6     7   Robert    3000      20  2023-06-25
7     3     Nick    1000      30  2015-09-15
8     9    Naman    4000      30  2020-01-20
9     1    Vikas    1000      30  2017-10-03
10   11   Dennis   41000      30  2024-01-05
11   12    Karan    2200      20  2018-06-16
12   13   Simran    1500      10  2019-12-19
13   14     Amit    2000      30  2022-04-09
14   15     Neha    1700      20  2021-07-22
15   16    Rahul    1200      10  2016-03-28
16   17    Divya    3000      30  2015-11-11
17   18   Rakesh    1800      10  2020-09-04
18   19   Monica    2500      20  2023-08-07
19   20     John    2300      30  2018-10-29
20   21    Sneha    2700      10  2022-12-14
21   22    David    1000      20  2017-02-17
22   23    Anita    1500      30  2019-05-21
23   24    Vinod    1800      10  2016-07-30
24   25    Meena    2000      20  2020-03-13
25   26    Harsh    1600      10  2021-09-25
26   27   Kavita    1400      30  2019-01-06
27   28    Mohan    1300      10  2015-04-17
28   29    Priya    1200      20  2023-02-11
29   30   Suresh    1100      10  2018-09-09
30   31     Rani    1900      20  2022-11-03
31   32     Ajay    2100      10  2020-06-26
32   33    Nidhi    2400      30  2016-05-12
33   34    Vivek    2000      20  2017-07-31
34   35    Seema    3000      10  2021-10-15
35   36     Ritu    3200      20  2023-05-01
36   37    Kunal    2800      30  2015-08-22
37   38     Alok    2700      10  2019-03-02
38   39   Poonam    2600      20  2022-02-05
39   40     Yash    2500      30  2020-07-19
40   41     Nina    2300      20  2018-12-28
41   42    Tarun    2200      10  2021-01-09
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
45   46    Manoj    1700      30  2019-07-24
46   47    Payal    1600      20  2015-10-10

In [11]:
df1=df[['eno','salary']].head()
df1

   eno  salary
0   10    1000
1    2    1000
2    8    1000
3    4    1000
4    5    2000

In [16]:
df.tail()

    eno    ename  salary  deptno         doj
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
45   46    Manoj    1700      30  2019-07-24
46   47    Payal    1600      20  2015-10-10

In [18]:
df=pd.read_csv('emp.csv',header=1)
df

    10    Amber   1000  10.1  2018-05-14
0    2     Amar   1000    10  2017-03-22
1    8    Sagar   1000    20  2020-11-30
2    4   Thomas   1000    10  2019-08-18
3    5     Jade   2000    10  2021-02-10
4    6    Smith   1000    10  2016-12-01
5    7   Robert   3000    20  2023-06-25
6    3     Nick   1000    30  2015-09-15
7    9    Naman   4000    30  2020-01-20
8    1    Vikas   1000    30  2017-10-03
9   11   Dennis  41000    30  2024-01-05
10  12    Karan   2200    20  2018-06-16
11  13   Simran   1500    10  2019-12-19
12  14     Amit   2000    30  2022-04-09
13  15     Neha   1700    20  2021-07-22
14  16    Rahul   1200    10  2016-03-28
15  17    Divya   3000    30  2015-11-11
16  18   Rakesh   1800    10  2020-09-04
17  19   Monica   2500    20  2023-08-07
18  20     John   2300    30  2018-10-29
19  21    Sneha   2700    10  2022-12-14
20  22    David   1000    20  2017-02-17
21  23    Anita   1500    30  2019-05-21
22  24    Vinod   1800    10  2016-07-30
23  25    Meena   2000    20  2020-03-13
24  26    Harsh   1600    10  2021-09-25
25  27   Kavita   1400    30  2019-01-06
26  28    Mohan   1300    10  2015-04-17
27  29    Priya   1200    20  2023-02-11
28  30   Suresh   1100    10  2018-09-09
29  31     Rani   1900    20  2022-11-03
30  32     Ajay   2100    10  2020-06-26
31  33    Nidhi   2400    30  2016-05-12
32  34    Vivek   2000    20  2017-07-31
33  35    Seema   3000    10  2021-10-15
34  36     Ritu   3200    20  2023-05-01
35  37    Kunal   2800    30  2015-08-22
36  38     Alok   2700    10  2019-03-02
37  39   Poonam   2600    20  2022-02-05
38  40     Yash   2500    30  2020-07-19
39  41     Nina   2300    20  2018-12-28
40  42    Tarun   2200    10  2021-01-09
41  43    Geeta   2100    30  2017-11-14
42  44    Ashok   1900    10  2016-06-08
43  45  Sanjana   1800    20  2023-03-17
44  46    Manoj   1700    30  2019-07-24
45  47    Payal   1600    20  2015-10-10

In [19]:
df=pd.read_csv('emp.csv',usecols=['eno','salary','doj'])
df

    eno  salary         doj
0    10    1000  2018-05-14
1     2    1000  2017-03-22
2     8    1000  2020-11-30
3     4    1000  2019-08-18
4     5    2000  2021-02-10
5     6    1000  2016-12-01
6     7    3000  2023-06-25
7     3    1000  2015-09-15
8     9    4000  2020-01-20
9     1    1000  2017-10-03
10   11   41000  2024-01-05
11   12    2200  2018-06-16
12   13    1500  2019-12-19
13   14    2000  2022-04-09
14   15    1700  2021-07-22
15   16    1200  2016-03-28
16   17    3000  2015-11-11
17   18    1800  2020-09-04
18   19    2500  2023-08-07
19   20    2300  2018-10-29
20   21    2700  2022-12-14
21   22    1000  2017-02-17
22   23    1500  2019-05-21
23   24    1800  2016-07-30
24   25    2000  2020-03-13
25   26    1600  2021-09-25
26   27    1400  2019-01-06
27   28    1300  2015-04-17
28   29    1200  2023-02-11
29   30    1100  2018-09-09
30   31    1900  2022-11-03
31   32    2100  2020-06-26
32   33    2400  2016-05-12
33   34    2000  2017-07-31
34   35    3000  2021-10-15
35   36    3200  2023-05-01
36   37    2800  2015-08-22
37   38    2700  2019-03-02
38   39    2600  2022-02-05
39   40    2500  2020-07-19
40   41    2300  2018-12-28
41   42    2200  2021-01-09
42   43    2100  2017-11-14
43   44    1900  2016-06-08
44   45    1800  2023-03-17
45   46    1700  2019-07-24
46   47    1600  2015-10-10

In [22]:
df.iloc[[46,45]]

    eno  salary         doj
46   47    1600  2015-10-10
45   46    1700  2019-07-24

In [23]:
df.iloc[5]

eno                6
salary          1000
doj       2016-12-01
Name: 5, dtype: object

In [24]:
type(df)

pandas.DataFrame

In [32]:
df=pd.read_csv('emp.csv',index_col='deptno')
df

        eno    ename  salary         doj
deptno
10       10    Amber    1000  2018-05-14
10        2     Amar    1000  2017-03-22
20        8    Sagar    1000  2020-11-30
10        4   Thomas    1000  2019-08-18
10        5     Jade    2000  2021-02-10
10        6    Smith    1000  2016-12-01
20        7   Robert    3000  2023-06-25
30        3     Nick    1000  2015-09-15
30        9    Naman    4000  2020-01-20
30        1    Vikas    1000  2017-10-03
30       11   Dennis   41000  2024-01-05
20       12    Karan    2200  2018-06-16
10       13   Simran    1500  2019-12-19
30       14     Amit    2000  2022-04-09
20       15     Neha    1700  2021-07-22
10       16    Rahul    1200  2016-03-28
30       17    Divya    3000  2015-11-11
10       18   Rakesh    1800  2020-09-04
20       19   Monica    2500  2023-08-07
30       20     John    2300  2018-10-29
10       21    Sneha    2700  2022-12-14
20       22    David    1000  2017-02-17
30       23    Anita    1500  2019-05-21
10       24    Vinod    1800  2016-07-30
20       25    Meena    2000  2020-03-13
10       26    Harsh    1600  2021-09-25
30       27   Kavita    1400  2019-01-06
10       28    Mohan    1300  2015-04-17
20       29    Priya    1200  2023-02-11
10       30   Suresh    1100  2018-09-09
20       31     Rani    1900  2022-11-03
10       32     Ajay    2100  2020-06-26
30       33    Nidhi    2400  2016-05-12
20       34    Vivek    2000  2017-07-31
10       35    Seema    3000  2021-10-15
20       36     Ritu    3200  2023-05-01
30       37    Kunal    2800  2015-08-22
10       38     Alok    2700  2019-03-02
20       39   Poonam    2600  2022-02-05
30       40     Yash    2500  2020-07-19
20       41     Nina    2300  2018-12-28
10       42    Tarun    2200  2021-01-09
30       43    Geeta    2100  2017-11-14
10       44    Ashok    1900  2016-06-08
20       45  Sanjana    1800  2023-03-17
30       46    Manoj    1700  2019-07-24
20       47    Payal    1600  2015-10-10

In [31]:
df

        eno    ename  salary         doj
deptno
10       10    Amber    1000  2018-05-14
10        2     Amar    1000  2017-03-22
20        8    Sagar    1000  2020-11-30
10        4   Thomas    1000  2019-08-18
10        5     Jade    2000  2021-02-10
10        6    Smith    1000  2016-12-01
20        7   Robert    3000  2023-06-25
30        3     Nick    1000  2015-09-15
30        9    Naman    4000  2020-01-20
30        1    Vikas    1000  2017-10-03
30       11   Dennis   41000  2024-01-05
20       12    Karan    2200  2018-06-16
10       13   Simran    1500  2019-12-19
30       14     Amit    2000  2022-04-09
20       15     Neha    1700  2021-07-22
10       16    Rahul    1200  2016-03-28
30       17    Divya    3000  2015-11-11
10       18   Rakesh    1800  2020-09-04
20       19   Monica    2500  2023-08-07
30       20     John    2300  2018-10-29
10       21    Sneha    2700  2022-12-14
20       22    David    1000  2017-02-17
30       23    Anita    1500  2019-05-21
10       24    Vinod    1800  2016-07-30
20       25    Meena    2000  2020-03-13
10       26    Harsh    1600  2021-09-25
30       27   Kavita    1400  2019-01-06
10       28    Mohan    1300  2015-04-17
20       29    Priya    1200  2023-02-11
10       30   Suresh    1100  2018-09-09
20       31     Rani    1900  2022-11-03
10       32     Ajay    2100  2020-06-26
30       33    Nidhi    2400  2016-05-12
20       34    Vivek    2000  2017-07-31
10       35    Seema    3000  2021-10-15
20       36     Ritu    3200  2023-05-01
30       37    Kunal    2800  2015-08-22
10       38     Alok    2700  2019-03-02
20       39   Poonam    2600  2022-02-05
30       40     Yash    2500  2020-07-19
20       41     Nina    2300  2018-12-28
10       42    Tarun    2200  2021-01-09
30       43    Geeta    2100  2017-11-14
10       44    Ashok    1900  2016-06-08
20       45  Sanjana    1800  2023-03-17
30       46    Manoj    1700  2019-07-24
20       47    Payal    1600  2015-10-10